/* eslint-disable @next/next/no-img-element */
import Cookies from "js-cookie";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { Fragment, useEffect, useState } from "react";
import Button from "../../components/Button";
import { Footer } from "../../components/Footer";
import { Stories } from "../../components/Stories";
import { Statistics } from "../../components/Statistics";
import { Navbar } from "../../components/Navbar";
import { getData } from "../../utils/fetchData";
import moment from "moment/moment";
import { formatDate } from "../../utils/formatDate";
import { CardEvent } from "../../components/CardEvent";
import { formatCurrency } from "../../utils/formatCurrency";

export default function DetailId({ detailPage, id }) {
  const [data, setData] = useState([]);

  console.log(detailPage.tickets);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await getData("api/v1/events");

        setData(res.data);
      } catch (err) {}
    };

    fetchData();
  }, []);

  const router = useRouter();

  const handleSubmit = (ticketId, organizer) => {
    const token = Cookies.get("token");
    if (!token) {
      return router.push("/signin");
    } else {
      router.push(
        `/checkout/${id}?ticketId=${ticketId}&organizer=${organizer}`
      );
    }
  };

  return (
    <>
      <Head>
        <title>Kaguka Foramu || Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <div className="preview-image bg-navy text-center">
        <img
          src={`${process.env.NEXT_PUBLIC_API}/${detailPage.image.name}`}
          className="img-content"
          alt="kaguka-detail"
        />
      </div>
      <div className="details-content container">
        <div className="d-flex flex-wrap justify-content-lg-center gap">
          <div className="d-flex flex-column description">
            <div className="headline">{detailPage.title}</div>
            <br />
            <div className="event-details">
              <h6>Event Details</h6>
              <p className="details-paragraph">{detailPage.about}</p>
            </div>
            <div className="keypoints">
              {detailPage.keyPoint.map((key, i) => {
                return (
                  <div className="d-flex align-items-start gap-3" key={i}>
                    <img src="/icons/ic-check.svg" alt="semina" />
                    <span>{key}</span>
                  </div>
                );
              })}
            </div>
            <div className="map-location">
              <h6>Event Location</h6>
              <div className="map-placeholder">
                <div className="maps">
                  <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d63536.63871717301!2d95.32870249999999!3d5.5611019!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3040377ae63dbcdf%3A0x3039d80b220cb90!2sBanda%20Aceh%2C%20Banda%20Aceh%20City%2C%20Aceh!5e0!3m2!1sen!2sid!4v1667287348245!5m2!1sen!2sid"
                    width="550"
                    height="300"
                    style={{ border: 0 }}
                    allowfullscreen=""
                    loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"
                  ></iframe>
                  <div
                    className="absolute d-flex justify-content-center align-items-center"
                    id="hoverMe"
                  >
                    <a href="#" className="btn-navy" id="btn-maps">
                      View in Google Maps
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="d-flex flex-column card-event">
            <div>

            </div>
            <h6>Your Speaker</h6>
            <div className="d-flex align-items-center gap-3 mt-3">
              <img
                src={`${process.env.NEXT_PUBLIC_API}/${detailPage?.talent?.image?.name}`}
                alt="speaker"
                width="60"
                style={{ borderRadius: "50%" }}
              />
              <div>
                <div className="speaker-name">{detailPage?.talent?.name}</div>
                <span className="occupation">{detailPage?.talent?.role}</span>
              </div>
            </div>
            <hr />

            <div className="d-flex gap-3 align-items-center card-details">
              <img src="/icons/ic-marker.svg" alt="semina" />{" "}
              {detailPage.venueName}
            </div>
            <div className="d-flex gap-3 align-items-center card-details">
              <img src="/icons/ic-time.svg" alt="semina" />{" "}
              {moment(detailPage.date).format("HH.MM A")}
            </div>
            <div className="d-flex gap-3 align-items-center card-details">
              <img src="/icons/ic-calendar.svg" alt="semina" />{" "}
              {formatDate(detailPage.date)}
            </div>
            <hr />
            <h5 className="mb-3">Ticket Type</h5>

            {detailPage.tickets.map((ticket, index) => (
              <Fragment key={index}>
                {ticket.statusTicketCategories ? (
                  <div className="typeEvent">
                    <h6 className="type-name">{ticket.type}</h6>
                    <div className="typeEvent-detail">
                      <div className="price">
                        {ticket.price === 0
                          ? "free"
                          : `${formatCurrency(ticket.price)}`}
                        <span>/person</span>
                      </div>
                      {detailPage.stock !== 0 && (
                        <Button
                          action={() =>
                            handleSubmit(ticket._id, detailPage.organizer)
                          }
                          className="btn-event"
                        >
                          JOIN NOW
                        </Button>
                      )}
                    </div>
                  </div>
                ) : (
                  ""
                )}
              </Fragment>
            ))}
          </div>
        </div>
      </div>

      <CardEvent data={data} title="Similiar Events" subTitle="Next One" />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData(`api/v1/events/${context.params.id}`);

  const res = req.data;
  console.log(res);

  return {
    props: { detailPage: res, id: context.params.id },
  };
}
