import Head from "next/head";
import { Header } from "../components/Header";
import { Brand } from "../components/Brand";
import { Stories } from "../components/Stories";
import { Statistics } from "../components/Statistics";
import { Footer } from "../components/Footer";
import { CardEvent } from "../components/CardEvent";
import { getData } from '../utils/fetchData';

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Brand />
        <CardEvent data={data} title='Featured Events' subTitle='Grow Today' />
        <Stories />
        <Statistics />
        <Footer />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const req = await getData('api/v1/events');
  const res = req.data;

  return {
    props: { data: res },
  };
}
